name: sirenang
version: 1.0.0+1
publish_to: none
description: A new Flutter project Sirenang
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^3.0.1
  carousel_slider: ^4.2.1
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
    
  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  

